import type { Metadata } from "next";
import { Inter } from "next/font/google";
import type { PropsWithChildren } from "react";
import "~/app/core/shared/globals.css";
import JotaiProvider from "~/app/core/shared/hook/provider/jotai-provider";
import ReactQueryProvider from "~/app/core/shared/hook/provider/react-query-provider";
import RecoilProvider from "~/app/core/shared/hook/provider/recoil-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo"
};

export default function RootLayout({
  children
}: Readonly<PropsWithChildren<object>>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <JotaiProvider>
          <RecoilProvider>
            <ReactQueryProvider>{children}</ReactQueryProvider>
          </RecoilProvider>
        </JotaiProvider>
      </body>
    </html>
  );
}
