import Footer from "@/app/core/shared/components/footer";
import SWRProvider from "@/app/core/shared/components/swr-provider";
import "@/app/core/shared/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SWRProvider>{children}</SWRProvider>
        <Footer />
      </body>
    </html>
  );
}
