import { MSWComponent } from "@/app/shared/components/msw-component";
import "@/app/shared/globals.css";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MSWComponent />
      <body>{children}</body>
    </html>
  );
}
