#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

COMMIT_MESSAGE_FILE=$1
COMMIT_MESSAGE=$(cat "$COMMIT_MESSAGE_FILE")

echo "❤️‍🩹 Commit Message: $COMMIT_MESSAGE"

# 커밋 메시지 검사 실행
npx commitlint --edit $1

# commitlint 실행 결과에 따라 스크립트 종료 코드 설정
if [ $? -eq 0 ]; then
  echo "🔆 Commit message meets the convention 🔆"
  exit 0
else
  echo "❌ Commit message does not meet the convention ❌"
  exit 1
fi

