#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

START_TIME=$(date "+%Y-%m-%d %H:%M:%S")
echo "🔍 [$START_TIME] commit 이전에 lint 규칙을 적용합니다..."

#  staged 상태인 파일들은 모두 검사합니다.
if npx lint-staged; then
END_TIME=$(date "+%Y-%m-%d %H:%M:%S")
echo "✅ [$END_TIME] 모든 lint 규칙이 성공적으로 적용되었습니다."
exit 0
else
  END_TIME=$(date "+%Y-%m-%d %H:%M:%S")
echo "❌ [$END_TIME] lint 규칙 검사에서 오류가 발생했습니다."
exit 1
fi
